### ISSUE TITLE
Fuel Types pages

### ISSUE THREAD

**Issue by maloufabmob** [fabmob/myc-emissions-calculator#12]
## Introduction 

Modifying the contents on the page where users can combine fuel types and transport categories based on what exists on their territory

**Comment by maloufabmob** [comment]
- [ ] Restrict the choice of fuels for some transport categories (some combination can't exist) 
_(-> to be validated by ifeu)_
- [ ] Add text contents to explain the step @maloufabmob 
- [x]  Add hydrogen in fuel types

**Comment by maloufabmob** [comment]
for the task Add hydrogen in fuel types : it is necessary to get the emissions factors from ifeu

**Comment by TTalex** [comment]
Emissions factors are available in MYC tool v1.4.

**Comment by TTalex** [comment]
Hydrogen support added with commit https://github.com/fabmob/myc-emissions-calculator/commit/449eeed71ef07081f7690beca855fb73fd4255fe
