### ISSUE TITLE
Input checks

### ISSUE THREAD

**Issue by maloufabmob** [fabmob/myc-emissions-calculator#21]
## Introduction 

All of the tasks that can allow the users to make sure they are filling out the tool properly

**Comment by maloufabmob** [comment]
- [ ] Add order of magnitude for the values @maloufabmob 
_(-> contents / numbers should be validated by ifeu)_

**Comment by TTalex** [comment]
Here are the checks I could identify in the Excel tool

| input | min value | max value | note |
| --- | --- | --- | --- |
| population | 100 | 2000000000 | no decimals |
| gdp | 1 | 1E+029 |  |
| vkt | 0 | 1E+022 |  |
| fleet approach: vehicle stock (private car) | 0 | population*(700/1000) |  |
| fleet approach: vehicle stock (individual taxi) | 0 | population*(100/1000) |  |
| fleet approach: vehicle stock (motorcycle) | 0 | population*(1500/1000) |  |
| fleet approach: vehicle stock (others) | 0 | 1E+033 |  |
| fleet approach: average mileage | 1 | 3000000 |  |
| occupancy (private car & Individual taxi) | 0.5 | 10 |  |
| occupancy (motorcycle) | 0.5 | 5 |  |
| occupancy (motorcycle taxi) | 0.2 | 5 |  |
| occupancy (minibus) | 1 | 50 |  |
| occupancy (bus) | 1 | 100 |  |
| occupancy (brt) | 1 | 200 |  |
| occupancy (long distance train, urban train metro) | 1 | 100000 |  |
| load (very light lcv & lcv) | 0.01 | 100 |  |
| load (solo truck & articulated truck) | 0.01 | 200 |  |
| load (freight train) | 0.01 | 1000000000 |  |
| Average fuel consumption (non electric fuels, private car & individual taxi) | 2 | 20 | For hybrid, minimal value is 0.5 for taxis only, probably a bug. No checks on lpg & ng for individual taxis either |
| Average fuel consumption (electric, private car & individual taxi) | 1 | 100 |  |
| Average fuel consumption (non electric fuels, moto & moto taxi) | 1 | 15 |  |
| Average fuel consumption (non electric fuels, minibus) | 2 | 40 | no checks on lpg & ng |
| Average fuel consumption (Diesel, bus & BRT) | 2 | 70 |  |
| Average fuel consumption (non electric fuels, very light LCV & LCV) | 2 | 30 | no checks on lpg & ng |
| Average fuel consumption (Diesel, Solo truck & articulated truck) | 2 | 60 |  |
| co2 content of electricity production (road & train) | 0 | 2000 | first cell for train has no check, probably a bug |
