### ISSUE TITLE
Implementation scenarios

### ISSUE THREAD

**Issue by maloufabmob** [fabmob/myc-emissions-calculator#22]
## Introduction

After the work on UX design, adding the features of the scenarios modelling

**Comment by maloufabmob** [comment]
Impl Input à partir d’un logiciel de planification de transports 
-- 
Impl 1. Avoid
Impl 2. Shift 
Impl Results of the transport demand measures
Impl 3. Improve: Penetration of alternative energies
Impl 4. Improve: Adjustment of fuel/energy consumption

**Comment by TTalex** [comment]
Included in MVP2 Design
