### ISSUE TITLE
Accounts Managements

### ISSUE THREAD

**Issue by maloufabmob** [fabmob/myc-emissions-calculator#27]
## Introduction

How to manage the different accounts and their different rights and accesses

**Comment by maloufabmob** [comment]
- [x] Create a dedicated access for MYC implementing partners to follow the filling of the calculator 
- [x] Tracking table
- [ ] Identification of administrator accounts

**Comment by maloufabmob** [comment]
Longer-term task : 

- [ ] Create an admin Interface

**Comment by TTalex** [comment]
The get started page was getting pretty good at tracking progress on projects. I believe it can be used as a tracking table

I added a special user role "app-admin", giving the following benefits:
* All existing projects are displayed on the get started page
* All existing projects can be validated, edited or deleted

I've set up both fabmob accounts as admins to test it
