### ISSUE TITLE
[inv./étapes] déplacer load et trip length dans étapes additionnelles et expliquer leur rôle

### ISSUE THREAD

**Issue by TTalex** [fabmob/myc-emissions-calculator#37]
Étape: 
- nul

Choses à produire:
- nouvelles étapes (structure et contenus)

**Comment by TTalex** [comment]
Décision: les séparer - et ainsi profiter d'une page entière sur trip length pour faire un blabla sur les proxys

On garde load en l'état, on met trip length au début du scénario.

TODO: Rédiger un texte explicatif

**Comment by maloufabmob** [comment]
Nous avons acté le 10 mai que load restait dans l'étapier de l'inventaire et que trip length était facultatif, mais qu'on explicitait son rôle à venir dans le calcul des émissions liées aux scénarios (+ collecte de la donnée à l'étape du diag SUMP).
