### ISSUE TITLE
[inv./intro] (F) détailler calculs dans lesquels required data sont utilisées

### ISSUE THREAD

**Issue by TTalex** [fabmob/myc-emissions-calculator#40]
Étape: 
- nul

Choses à produire:
- liste pour chaque calcul : données et formules associées

**Comment by TTalex** [comment]
C'est un peu vague 😕

**Comment by maloufabmob** [comment]
Solution proposée : expliciter les méthodes de calcul à l'étape entre la page projet et le remplissage des premières données : 
- pour inventaire, schéma ASIF + expliciter load qui sert pour part modal
- pour BAU, projections de croissance par rapport à l'inventaire
- pour scénario climat, lien entre stratégie ASI et méthode ASIF
