### ISSUE TITLE
Welcome page

### ISSUE THREAD

**Issue by maloufabmob** [fabmob/myc-emissions-calculator#5]
## Introduction 

Modify contents on the first page users see as they arrive on the website

**Comment by maloufabmob** [comment]
- [x] Add logos from the different organizations of the MobiliseYourCity partnership  @TTalex 
_(-> it's possible to change the format of the provided logos keeping their order and the groups. inputs : https://cloud.fabmob.io/s/npBq9SFMFksoWYc)_
- [x] Add a world map with MYC partners countries and cities @maloufabmob
_(define if static (Myc website map) or dynamic)_
- [ ] Add description of the MobiliseYourCity partnership @maloufabmob 
 _(check Myc website map)_

**Comment by TTalex** [comment]
I added a static map for now.
I also redesigned the page in the process.
