### ISSUE TITLE
Project Management page

### ISSUE THREAD

**Issue by maloufabmob** [fabmob/myc-emissions-calculator#6]
## Introduction 

Create a page where users can manage the project(s) they are working on

**Comment by maloufabmob** [comment]
- [x] Add feature to remove a project
- [x] Add feature to validate a project (before publishing)
- [x] Add feature to consult a project from an other user

**Comment by TTalex** [comment]
Some notes:
* A validated project is automatically published for now.
* Only project with all steps completed can be validated, they must reach the overview page
* A validated project can still be modified by its author
* Other users have access to validated projects, but cannot modify them. The inputs can still be changed, but nothing is saved.

Remaining TODOs (with less priority):
- [ ] Add a validation button to the overview page (related: https://github.com/fabmob/myc-emissions-calculator/issues/15)
- [ ] Publishing validated projects shouldn't be automatic

**Comment by TTalex** [comment]
Turns out publishing validated project should be automatic, since they are mandated by public authorities believing on open data.

See MVP2 for a followup on UX/UI questions
