### ISSUE TITLE
Log in page

### ISSUE THREAD

**Issue by maloufabmob** [fabmob/myc-emissions-calculator#7]
## Introduction 

Modifying the page where users can create an account through KeyCloak

**Comment by maloufabmob** [comment]
- [x] Adapt the page to the graphic charter

**Comment by maloufabmob** [comment]
- [ ] Adapt the page to the graphic charter

**Comment by TTalex** [comment]
I did something simple that should be in line with the rest of the UI.

Based on https://github.com/lukin/keywind
