### ISSUE TITLE
Create A Project page

### ISSUE THREAD

**Issue by maloufabmob** [fabmob/myc-emissions-calculator#8]
## Introduction 

Modifying contents on the page where users can create a new project

**Comment by maloufabmob** [comment]
- [x] Add a list of suggested cities  @TTalex  
- [x] Remove French Overseas Departements from the list @TTalex 
- [x] Allow users to turn back on this page @TTalex 
- [ ] Clarify what is a partner city @maloufabmob 
- [ ] Modify the shadow mark to orientate the name of the project 
- [ ] Validate the fields to fill 
_(-> maybe others are necessary -> check the GIZ database)_

**Comment by maloufabmob** [comment]
- [x] Add feature to allow the user to custom time lapses
 
_-> is this feature on this page ?_

**Comment by TTalex** [comment]
Fields present in GIZ transport db that we do not have:
* Region (e.g. Latin America)
* Author (e.g. ifeu / giz): I guess that could be our 'owner' field, but it's the user email for us, not the company

**Comment by TTalex** [comment]
See MVP2 for a followup on UI/UX.
Missing fields will not be added, as they are not a priority.
