### ISSUE TITLE
Transport Categories

### ISSUE THREAD

**Issue by maloufabmob** [fabmob/myc-emissions-calculator#9]
Modifying contents on the page where users can select the existing transport categories on their territory

**Comment by maloufabmob** [comment]
- [ ] Clarify the contents explaining that customizing transport category allows to merge existing categories (as long as the distribution of the fuels are similar) / Explain that the tool bases the emissions calculation on the emissions factor linked to the fuel @maloufabmob 
- [ ] Change "moto-taxi" name ? _(-> validate with MYC)_
- [x] Add "cargobike" and "coach" to the existing categories @TTalex

**Comment by TTalex** [comment]
We're missing some definitions for the new categories

**Comment by TTalex** [comment]
Cargobike and coach added in commit https://github.com/fabmob/myc-emissions-calculator/commit/7bed6568195291b50ea4195164100851b1267cf7

Icons and definition have been arbitrarily set:
"🚲 Cargo bike": 'Cycle designed for transporting loads'
"🚌 Coach": 'Bus used for longer-distance service.'

**Comment by TTalex** [comment]
See new MVP2 design for a followup
